---
- name: Add filebeat to source list
  apt_repository:
    repo: deb https://packages.elastic.co/beats/apt stable main
    state: present
    update_cache: yes
  become: yes

- name: Install Filebeat
  apt:
    name: filebeat
    force: true
    state: present
  become: yes

- name: Enable filebeat on boot
  service:
    name: filebeat
    enabled: yes
  become: yes
  notify: restart filebeat
