---
- name: Import the Elasticsearch public GPG key into apt
  apt_key:
    url: 'https://packages.elastic.co/GPG-KEY-elasticsearch'

- name: Add specified repository into sources list using specified filename.
  apt_repository:
    repo: deb http://packages.elastic.co/elasticsearch/2.x/debian stable main
    state: present
    filename: elasticsearch-2.x.list
    update_cache: yes

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    force: true
    state: latest
