---
- name: Add Kibana to source list
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
    state: present
    update_cache: yes
  become: yes

- name: Install kibana
  apt:
    name: kibana
    force: true
    state: latest
  become: yes

- name: copy kibana.yml
  copy:
    src: kibana.yml
    dest: /opt/kibana/config/
    force: yes
  notify:
    - restart kibana
  become: yes

- name: Enable kibana on boot
  service:
    name: kibana
    enabled: yes
  become: yes
